In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
file_path = r"E:\Nasa Space App 2025\Hunting_For_Exoplanets_With_AI_Nasa2025\DataSet\K2\k2_data.csv"
df = pd.read_csv(file_path, comment="#")
df.head(10)

,pl_name,hostname,default_flag,disposition,disp_refname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,BD+20 594 b,BD+20 594,0,CONFIRMED,Espinoza et al. 2016,1.0,1.0,Transit,2016.0,K2,...,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249,2018-04-25,2018-03,2018-02-15
1,BD+20 594 b,BD+20 594,0,CONFIRMED,Espinoza et al. 2016,1.0,1.0,Transit,2016.0,K2,...,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249,2018-04-25,2016-10,2016-07-28
2,BD+20 594 b,BD+20 594,1,CONFIRMED,Espinoza et al. 2016,1.0,1.0,Transit,2016.0,K2,...,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249,2018-04-25,2017-03,2018-04-26
3,EPIC 201111557.01,EPIC 201111557,0,CANDIDATE,Livingston et al. 2018,1.0,0.0,Transit,2018.0,K2,...,-0.046,9.220,0.019,-0.019,11.3995,0.001307,-0.001307,2018-02-15,2018-03,2018-02-15
4,EPIC 201111557.01,EPIC 201111557,1,CANDIDATE,Livingston et al. 2018,1.0,0.0,Transit,2018.0,K2,...,-0.046,9.220,0.019,-0.019,11.3995,0.001307,-0.001307,2018-08-02,2018-08,2018-08-02
5,EPIC 201126503.01,EPIC 201126503,1,CANDIDATE,Vanderburg et al. 2016,1.0,0.0,Transit,2016.0,K2,...,-0.200,14.230,0.070,-0.070,17.8892,0.001662,-0.001662,2015-12-05,2016-01,2015-12-05
6,EPIC 201127519.01,EPIC 201127519,0,CANDIDATE,Livingston et al. 2018,1.0,0.0,Transit,2018.0,K2,...,-0.046,9.430,0.021,-0.021,11.4806,0.000478,-0.000478,2018-02-15,2018-03,2018-02-15
7,EPIC 201127519.01,EPIC 201127519,1,CANDIDATE,Livingston et al. 2018,1.0,0.0,Transit,2018.0,K2,...,-0.046,9.430,0.021,-0.021,11.4806,0.000478,-0.000478,2018-08-02,2018-08,2018-08-02
8,EPIC 201147085.01,EPIC 201147085,1,CANDIDATE,Kruse et al. 2019,1.0,0.0,Transit,2019.0,K2,...,-0.200,11.397,0.023,-0.023,NaN,NaN,NaN,2019-09-05,2019-09,2019-09-05
9,EPIC 201152065.01,EPIC 201152065,1,CANDIDATE,Kruse et al. 2019,1.0,0.0,Transit,2019.0,K2,...,-0.183,11.430,0.023,-0.023,13.9562,0.000535,-0.000535,2019-09-05,2019-09,2019-09-05

In [3]:
df.shape

(3992, 94)

In [4]:
DROP = [
    "pl_name","hostname","disp_refname","pl_refname","st_refname","sy_refname",
    "pl_pubdate","releasedate","rowupdate",
    "rastr","decstr",
    "discoverymethod","disc_facility",
    "default_flag","pl_controv_flag","ttv_flag","soltype","disc_year"
]
df = df.drop(columns=[c for c in DROP if c in df.columns], errors="ignore")

In [5]:
df.head(10)

,disposition,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,CONFIRMED,1.0,1.0,41.688644,0.003353,-0.003419,0.0,NaN,NaN,NaN,...,-1.2400,10.849,0.012,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249
1,CONFIRMED,1.0,1.0,41.685500,0.003000,-0.003100,0.0,0.241,0.019,-0.017,...,-1.2400,10.849,0.012,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249
2,CONFIRMED,1.0,1.0,41.685500,0.003000,-0.003000,0.0,NaN,NaN,NaN,...,-1.2400,10.849,0.012,-0.012,9.368,0.018,-0.018,10.8644,0.000249,-0.000249
3,CANDIDATE,1.0,0.0,2.302368,0.000105,-0.000103,0.0,NaN,NaN,NaN,...,-0.4598,11.727,0.046,-0.046,9.220,0.019,-0.019,11.3995,0.001307,-0.001307
4,CANDIDATE,1.0,0.0,2.301830,0.000280,-0.000300,0.0,NaN,NaN,NaN,...,-0.4598,11.727,0.046,-0.046,9.220,0.019,-0.019,11.3995,0.001307,-0.001307
5,CANDIDATE,1.0,0.0,1.194749,NaN,NaN,0.0,NaN,NaN,NaN,...,-16.3250,19.210,0.200,-0.200,14.230,0.070,-0.070,17.8892,0.001662,-0.001662
6,CANDIDATE,1.0,0.0,6.178369,0.000195,-0.000172,0.0,NaN,NaN,NaN,...,-0.7670,11.733,0.046,-0.046,9.430,0.021,-0.021,11.4806,0.000478,-0.000478
7,CANDIDATE,1.0,0.0,6.178870,0.000070,-0.000070,0.0,NaN,NaN,NaN,...,-0.7670,11.733,0.046,-0.046,9.430,0.021,-0.021,11.4806,0.000478,-0.000478
8,CANDIDATE,1.0,0.0,1.175890,0.000100,-0.000100,0.0,NaN,NaN,NaN,...,NaN,16.640,0.200,-0.200,11.397,0.023,-0.023,NaN,NaN,NaN
9,CANDIDATE,1.0,0.0,10.696600,0.002000,-0.002100,0.0,NaN,NaN,NaN,...,-1.3900,14.346,0.183,-0.183,11.430,0.023,-0.023,13.9562,0.000535,-0.000535